spring.application.name=keystone

spring.datasource.url=jdbc:postgresql://localhost:5432/keystone?options=-c%20timezone=Asia/Kolkata
spring.datasource.username=keystone_user
spring.datasource.password=keystone_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080

user.timezone=Asia/Kolkata